# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161007_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrepository',
            name='owner',
        ),
        migrations.RenameField(
            model_name='repositorysnippet',
            old_name='rating',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='repositorysnippet',
            name='language',
            field=models.CharField(default=None, max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repositorysnippet',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositorysnippet',
            name='repository',
            field=models.CharField(max_length=124),
        ),
        migrations.DeleteModel(
            name='UserRepository',
        ),
    ]
