# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161007_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorysnippet',
            name='lines',
            field=models.CharField(default='L0-L20', max_length=124),
            preserve_default=False,
        ),
    ]
