# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_repositorysnippet_lines'),
        ('users', '0004_auto_20161007_2047'),
    ]

    operations = [
    ]
