# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorysnippet',
            name='filename',
            field=models.CharField(default='', max_length=124),
            preserve_default=False,
        ),
    ]
